Computer Vision with Python, OpenCV, Pytorch

Using numpy

In [21]:
import numpy as np

In [10]:
a = np.array([1,2,3])

print(a)

element = a[1]
print(element)

[1 2 3]
2


In [11]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)

e = matrix[1,2]

print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [32]:
a = np.ones(5, dtype=np.int64)
print(a)
b = np.zeros(5)
print(b)

[1 1 1 1 1]
[0. 0. 0. 0. 0.]


In [23]:
empty_e = np.empty(5)
print(empty_e)

c = np.arange(100)
print(c)

[0. 0. 0. 0. 0.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [33]:
d = np.linspace(0,100, num=5, dtype=np.int64)
print(d)

[  0  25  50  75 100]


In [35]:
arr = np.array([3,1,2,4,5])
print(np.sort(arr))
print(np.sort(arr)[::-1])

[1 2 3 4 5]
[5 4 3 2 1]


In [41]:
arr = np.append(arr, 100)
print(arr)


[  3   1   2   4   5 100 100 100 100]
[  3   1   2   5 100 100 100 100]


In [44]:
arr = np.delete(arr, 3)
print(arr)

[  3   1   2 100 100 100]


In [49]:
arr1 = np.array([[3,2,1],[4,6,5],[9,7,8]])

sorted_arr = np.sort(arr1, axis=1)
print(sorted_arr)

sorted_arr2 = np.sort(arr1, axis=0)
print(sorted_arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [4 6 5]
 [9 7 8]]


In [51]:
arr1 = np.array([[3,2,1],[4,6,5],[9,7,8]])

sorted_arr = -np.sort(-arr1, axis=1)
print(sorted_arr)

sorted_arr2 = -np.sort(-arr1, axis=0)
print(sorted_arr2)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 7 8]
 [4 6 5]
 [3 2 1]]


In [54]:
arr3 = np.array([[1,2,3],[4,5,6]])

dim_arr3 = arr3.ndim
size_arr3 = arr3.size
shape_arr3 = arr3.shape
print(dim_arr3)
print(size_arr3)
print(shape_arr3)

2
6
(2, 3)


In [55]:
arr4 = np.array([1,2,3,4,5])
arr_float = arr4.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [58]:
arr = np.array([1,2,3,4,5,6])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [63]:
reshaped_arr = reshaped_arr.flatten()
print(reshaped_arr)

[1 2 3 4 5 6]


In [65]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [69]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [75]:
arr = np.array([1,2,3,4,5,6])
total = np.sum(arr)
print('Sum of array: ', total)
average = np.mean(arr)
print('Average: ', average)

max_val = np.max(arr)
min_val = np.min(arr)
print('Max value: ', max_val)
print('Min value: ', min_val)

std_deviation = np.std(arr)
print('Standard Deviation: ', std_deviation)

variance = np.var(arr)
print('Variance: ', variance)

Sum of array:  21
Average:  3.5
Max value:  6
Min value:  1
Standard Deviation:  1.707825127659933
Variance:  2.9166666666666665


In [77]:
arr1 = np.array([1,2,3])
arr2= np.array([4,5,6])
dot_product = np.dot(arr1, arr2)
print('Dot Product: ', dot_product)

Dot Product:  32
